use std::collections::{HashSet, HashMap};

use once_cell::sync::Lazy;

pub static SECTORS: Lazy<HashSet<&'static str>> = Lazy::new(|| {
    HashSet::from([
        "Communication Services",
        "Consumer Cyclical",
        "Consumer Staples",
        "Energy",
        "Financial Services",
        "Health Care",
        "Industrials",
        "Technology",
        "Basic Materials",
        "Real Estate",
        "Utilities",
    ])
});

pub static SECTOR_SYNONYMS: Lazy<HashMap<&'static str, &'static str>> = Lazy::new(|| {
    HashMap::from([
        ("Healthcare", "Health Care"),
        ("Financials", "Financial Services"),
        ("Materials", "Basic Materials"),
        ("Information Technology", "Technology"),
        ("Consumer Discretionary", "Consumer Cyclical"),
    ])
});

pub static COUNTRY_TO_REGION: Lazy<HashMap<&'static str, &'static str>> = Lazy::new(|| {
    HashMap::from([
        ("United States", "Americas"),
        ("Canada", "Americas"),
        ("Brazil", "Americas"),
        ("Chile", "Americas"),
        ("Colombia", "Americas"),
        ("Mexico", "Americas"),
        ("Peru", "Americas"),
        ("Argentina", "Americas"),
        ("Bermuda", "Americas"),
        ("Jamaica", "Americas"),
        ("Panama", "Americas"),
        ("Puerto Rico", "Americas"),
        ("Trinidad & Tobago", "Americas"),
        ("Austria", "Europe"),
        ("Belgium", "Europe"),
        ("Denmark", "Europe"),
        ("Finland", "Europe"),
        ("France", "Europe"),
        ("Germany", "Europe"),
        ("Ireland", "Europe"),
        ("Italy", "Europe"),
        ("Netherlands", "Europe"),
        ("Norway", "Europe"),
        ("Portugal", "Europe"),
        ("Spain", "Europe"),
        ("Sweden", "Europe"),
        ("Switzerland", "Europe"),
        ("United Kingdom", "Europe"),
        ("Czech Republic", "Europe"),
        ("Greece", "Europe"),
        ("Hungary", "Europe"),
        ("Poland", "Europe"),
        ("Croatia", "Europe"),
        ("Estonia", "Europe"),
        ("Iceland", "Europe"),
        ("Latvia", "Europe"),
        ("Lithuania", "Europe"),
        ("Romania", "Europe"),
        ("Serbia", "Europe"),
        ("Slovenia", "Europe"),
        ("Belarus", "Europe"),
        ("Bosnia Herzegovina", "Europe"),
        ("Bulgaria", "Europe"),
        ("Malta", "Europe"),
        ("Russia", "Europe"),
        ("Ukraine", "Europe"),
        ("Australia", "Pacific"),
        ("Hong Kong", "Pacific"),
        ("Japan", "Pacific"),
        ("New Zealand", "Pacific"),
        ("Singapore", "Pacific"),
        ("Israel", "Middle East"),
        ("Egypt", "Middle East"),
        ("Kuwait", "Middle East"),
        ("Qatar", "Middle East"),
        ("Saudi Arabia", "Middle East"),
        ("Turkey", "Middle East"),
        ("United Arab Emirates", "Middle East"),
        ("Bahrain", "Middle East"),
        ("Jorand", "Middle East"),
        ("Oman", "Middle East"),
        ("Lebanon", "Middle East"),
        ("Palestine", "Middle East"),
        ("China", "Asia"),
        ("India", "Asia"),
        ("Indonesia", "Asia"),
        ("Korea", "Asia"),
        ("Malaysia", "Asia"),
        ("Philippines", "Asia"),
        ("Taiwan", "Asia"),
        ("Thailand", "Asia"),
        ("Kazakhstan", "Asia"),
        ("Bangladesh", "Asia"),
        ("Pakistan", "Asia"),
        ("Sri Lanka", "Asia"),
        ("Vietnam", "Asia"),
        ("South Africa", "Africa"),
        ("Kenya", "Africa"),
        ("Mauritius", "Africa"),
        ("Morocco", "Africa"),
        ("Nigeria", "Africa"),
        ("Tunisia", "Africa"),
        ("Benin", "Africa"),
        ("Burkina Faso", "Africa"),
        ("Côte D'Ivoire", "Africa"),
        ("Guinea-Bissau", "Africa"),
        ("Mali", "Africa"),
        ("Niger", "Africa"),
        ("Senegal", "Africa"),
        ("Togo", "Africa"),
        ("Botzwana", "Africa"),
        ("Zimbabwe", "Africa"),
    ])
});

pub static COUNTRY_TO_MARKET: Lazy<HashMap<&'static str, &'static str>> = Lazy::new(|| {
    HashMap::from([
        ("United States", "Developed"),
        ("Canada", "Developed"),
        ("Brazil", "Emerging"),
        ("Chile", "Emerging"),
        ("Colombia", "Emerging"),
        ("Mexico", "Emerging"),
        ("Peru", "Emerging"),
        ("Argentina", "Standalone"),
        ("Bermuda", "Standalone"),
        ("Jamaica", "Standalone"),
        ("Panama", "Standalone"),
        ("Puerto Rico", "Standalone"),
        ("Trinidad & Tobago", "Standalone"),
        ("Austria", "Developed"),
        ("Belgium", "Developed"),
        ("Denmark", "Developed"),
        ("Finland", "Developed"),
        ("France", "Developed"),
        ("Germany", "Developed"),
        ("Ireland", "Developed"),
        ("Italy", "Developed"),
        ("Netherlands", "Developed"),
        ("Norway", "Developed"),
        ("Portugal", "Developed"),
        ("Spain", "Developed"),
        ("Sweden", "Developed"),
        ("Switzerland", "Developed"),
        ("United Kingdom", "Developed"),
        ("Czech Republic", "Emerging"),
        ("Greece", "Emerging"),
        ("Hungary", "Emerging"),
        ("Poland", "Emerging"),
        ("Croatia", "Frontier"),
        ("Estonia", "Frontier"),
        ("Iceland", "Frontier"),
        ("Latvia", "Frontier"),
        ("Lithuania", "Frontier"),
        ("Romania", "Frontier"),
        ("Serbia", "Frontier"),
        ("Slovenia", "Frontier"),
        ("Belarus", "Standalone"),
        ("Bosnia Herzegovina", "Standalone"),
        ("Bulgaria", "Standalone"),
        ("Malta", "Standalone"),
        ("Russia", "Standalone"),
        ("Ukraine", "Standalone"),
        ("Australia", "Developed"),
        ("Hong Kong", "Developed"),
        ("Japan", "Developed"),
        ("New Zealand", "Developed"),
        ("Singapore", "Developed"),
        ("Israel", "Developed"),
        ("Egypt", "Emerging"),
        ("Kuwait", "Emerging"),
        ("Qatar", "Emerging"),
        ("Saudi Arabia", "Emerging"),
        ("Turkey", "Emerging"),
        ("United Arab Emirates", "Emerging"),
        ("Bahrain", "Frontier"),
        ("Jorand", "Frontier"),
        ("Oman", "Frontier"),
        ("Lebanon", "Standalone"),
        ("Palestine", "Standalone"),
        ("China", "Emerging"),
        ("India", "Emerging"),
        ("Indonesia", "Emerging"),
        ("Korea", "Emerging"),
        ("Malaysia", "Emerging"),
        ("Philippines", "Emerging"),
        ("Taiwan", "Emerging"),
        ("Thailand", "Emerging"),
        ("Kazakhstan", "Frontier"),
        ("Bangladesh", "Frontier"),
        ("Pakistan", "Frontier"),
        ("Sri Lanka", "Frontier"),
        ("Vietnam", "Frontier"),
        ("South Africa", "Emerging"),
        ("Kenya", "Frontier"),
        ("Mauritius", "Frontier"),
        ("Morocco", "Frontier"),
        ("Nigeria", "Frontier"),
        ("Tunisia", "Frontier"),
        ("Benin", "Frontier"),
        ("Burkina Faso", "Frontier"),
        ("Côte D'Ivoire", "Frontier"),
        ("Guinea-Bissau", "Frontier"),
        ("Mali", "Frontier"),
        ("Niger", "Frontier"),
        ("Senegal", "Frontier"),
        ("Togo", "Frontier"),
        ("Botzwana", "Standalone"),
        ("Zimbabwe", "Standalone"),
    ])
});
